Repository nairnairnair/whats-cookin, pull requests merged in 2022-07, with the labels that each got.

#23 Add test file and add import statement
  src/data/recipes-test.js
  test/RecipeRepository-test.js
Labels: enhancement

#24 Condense beforeEach, add recipe data test, add RecipeRepository parameters
  src/classes/RecipeRepository.js
  src/data/recipes-test.js
  test/RecipeRepository-test.js
Labels: enhancement

#25 Add the tag test and listRecipeTag method
  src/classes/RecipeRepository.js
  src/data/recipes-test.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
Labels: enhancement

#26 Add method listRecipeNames
  src/classes/RecipeRepository.js
  test/RecipeRepository-test.js
Labels: enhancement

#27 Remove un-needed imports, remove comments, adjust spacing
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  test/RecipeRepository-test.js
Labels: enhancement

#49 Add a search bar, search icon, and new logo, as well as css
  dist/balanced-diet.png
  dist/index.html
  dist/loupe.png
  src/styles.css
Labels: enhancement

#50 Add pseudocode to the user class and 1 test + basic beforeEach skeleton to user test file
  src/classes/User.js
  test/User-test.js
Labels: enhancement

#51 Create HTML elements and style for recipe view
  dist/index.html
  src/styles.css
Labels: enhancement

#52 Add user tests and addRecipeToCook method to user.js
  src/classes/User.js
  test/User-test.js
Labels: enhancement

#53 Refactor and add tests to User-test file
  src/classes/User.js
  test/User-test.js
Labels: enhancement

#69 Add removeRecipeToCook function and relevant tests
  src/classes/User.js
  test/User-test.js
Labels: enhancement

#71 Feature/user filterbytag
  src/classes/User.js
  test/User-test.js
Labels: enhancement

#73 Add project README & organize CSS
  README.md
  dist/index.html
  src/styles.css
Labels: enhancement

#75 Update class and IDs, add css and html sections
  dist/index.html
  src/styles.css
Labels: enhancement

#77 Add the populateAllRecipesView function to scripts, add HTML, and alt…
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#80 Add button for saving recipes
  dist/index.html
  src/styles.css
Labels: enhancement

#81 Achieve functionality for displaying a chosen recipe by click
  dist/index.html
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/scripts.js
  src/styles.css
  test/RecipeRepository-test.js
Labels: enhancement

#86 write method to show ingredient name, quantity, and unit in display c…
  src/classes/Recipe.js
  src/scripts.js
  test/RecipeRepository-test.js
Labels: enhancement

#88 Add query selector, event listener and function for saving recipes
  src/scripts.js
  src/styles.css
Labels: enhancement

#92 Add browser tab icon
  dist/index.html
Labels: enhancement

#94 Add extra features to our README
  README.md
Labels: enhancement

#98 Feature/search bar functionality
  dist/index.html
  src/scripts.js
Labels: enhancement

#99 Created filtered view to keep dom manipulation separate from home view
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#100 Creates additional filter buttons and input to be used in the saved view
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#101 Add finishing touches on main section CSS and Header section
  dist/index.html
  src/styles.css
Labels: enhancement

#103 Refactor JS, CSS, and HTML to clean up spacing, syntax, and commented…
  dist/index.html
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/scripts.js
  src/styles.css
Labels: enhancement

#105 Refactored menu and image box CSS and html
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#118 Refactor/unit test refactoring
  test/Ingredient-test.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
Labels: enhancement

#121 Add CSS styling
  src/styles.css
Labels: enhancement

#122 Rename hover property and general cleanup
  src/styles.css
Labels: enhancement

#130 Saved view bugfix3
  src/scripts.js
Labels: bug

#143 Remove comments, refactor headings, modify indentation
  src/scripts.js
Labels: enhancement

#144 Add pantry file to src file
  src/classes/pantry.js
Labels: enhancement

#148 Bugfix/search filter
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/scripts.js
Labels: enhancement

#149 Add hidden delete button to saved recipes page
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: bug

#150 Refactor to fix tag filter methods bug and add additional recipe-repo…
  src/classes/RecipeRepository.js
  src/classes/User.js
  test/RecipeRepository-test.js
Labels: enhancement

#152 Refactor User-test to account for changes to filter functions (filter…
  test/RecipeRepository-test.js
  test/User-test.js
Labels: enhancement

#153 Create Pantry-test file and describe/it blocks for each user story and method requirement
  test/Pantry-test.js
Labels: enhancement

#154 Add sad path methods and testing to verify error handling
  src/classes/RecipeRepository.js
  src/classes/User.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: enhancement

#155 Add deleteChosenRecipe function, modify saveChosenRecipe and HTML and CSS
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#156 Add method and testing for returnIngredientNamesAndAmounts
  src/classes/Pantry.js
  test/Pantry-test.js
Labels: enhancement

#165 Write pantry method to return whether a user can cook a recipe
  src/classes/Pantry.js
  test/Pantry-test.js
Labels: enhancement

#166 Add small pantry view, buttons, instructions, event listeners, and evaluation helper function
  dist/check.svg.png
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#167 Refactor pantry method for returning if recipe can be cooked
  src/classes/Pantry.js
  test/Pantry-test.js
Labels: enhancement

#168 Refactor returnIfRecipeIsCookable
  src/classes/Pantry.js
  test/Pantry-test.js
Labels: enhancement

#169 Write dom manipulation for Pantry display in saved vew
  dist/index.html
  src/classes/Pantry.js
  src/scripts.js
Labels: enhancement

#170 Fix bug for recipes with an apostrophe in title
  src/classes/Pantry.js
  src/scripts.js
Labels: enhancement

#171 Correct save/delete button and message display behavior
  dist/index.html
  src/scripts.js
Labels: bug, enhancement

#176 Add form and button and event listener for adding recipes
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#177 Create HTML elements for posting in pantry
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#179 Add cookRecipe FUNtion and related button and event listener
  dist/index.html
  src/scripts.js
Labels: enhancement

#180 Implement error handling and general refactoring
  dist/index.html
  src/classes/Pantry.js
  src/scripts.js
  src/styles.css
  test/Pantry-test.js
Labels: enhancement

#181 Fix issue where adding ingredients wiped out saved recipes
  src/scripts.js
Labels: bug, enhancement
